# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- main

#pool:
#  vmImage: 'windows-latest'

pool: 
  name: MySelfHostedAgent
  demands:
   - Agent.Name -equals BambooAgent

variables:
  vsHomeDir: 'C:/Program Files/Microsoft Visual Studio/2022/Professional'
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  enabled: false
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: CmdLine@2
  enabled: true
  displayName: 'VS Build - Release'
  inputs:
    script: |
      echo 'Build starting..'
      call "$(vsHomeDir)/VC/Auxiliary/Build/vcvarsall.bat" x64
      call "$(vsHomeDir)/Common7/IDE/devenv.com" "$(Build.Repository.LocalPath)\BattleShip.sln" /rebuild Release


